### get all college
GET  http://localhost:4000/api/vice-chancellor-cv


### get college by id
GET  http://localhost:4000/api/vice-chancellor-cv/640457f914f7a3bce526a770

### delete college
DELETE   http://localhost:4000/api/vice-chancellor-cv/64043dab5c74c6390165b5d3

###  create college
POST  http://localhost:4000/api/vice-chancellor-cv
Content-Type: application/json

{
    "titleAr": "medicen",
    "titleEn": "name en",
    "descriptionAr": "descriptionAr",
    "descriptionEn": "description English",
    "image": "image"
}

###  update  college
PUT  http://localhost:4000/api/vice-chancellor-cv/640457f914f7a3bce526a770
Content-Type: application/json

{
    "titleAr": "medicen update"
}