### get all college
GET  http://localhost:4000/api/electronic-service


### get college by id
GET  http://localhost:4000/api/electronic-service/6409ae4db92f75d7e2caaf64

### delete college
DELETE   http://localhost:4000/api/electronic-service/6409ae4db92f75d7e2caaf64

###  create college
POST  http://localhost:4000/api/electronic-service
Content-Type: application/json

{
    "titleAr": "medicen",
    "titleEn": "name en",
    "icon": "descriptionAr"
}

###  update  college
PUT  http://localhost:4000/api/electronic-service/6409ae4db92f75d7e2caaf64
Content-Type: application/json

{
    "titleAr": "medicen update"
}