### get all college
GET  http://localhost:4000/api/vision-mission

sss
### get college by id
GET  http://localhost:4000/api/vision-mission/6401af0be2dc006818125376

### delete college
DELETE   http://localhost:4000/api/vision-mission/6408485bf0c58396c7756543

###  create college
POST  http://localhost:4000/api/vision-mission
Content-Type: application/json

{
    "titleAr": " المعرفية الرائدة ",
    "titleEn": " المعرفية الرائدة ",
    "descriptionAr": "تطمح جامعة بحري إلى أن تصبح المؤسسة المعرفية الرائدة في إفريقيا والعالم العربي.",
     "icon": "icon",
     "seqNo": 1,
    "descriptionEn": "تطمح جامعة بحري إلى أن تصبح المؤسسة المعرفية الرائدة في إفريقيا والعالم العربي."
}

###  update  college
PUT  http://localhost:4000/api/vision-mission/6401af0be2dc006818125376
Content-Type: application/json

{
    "titleAr": "medicen update"
}


###

POST   http://localhost:4000/api/vision-mission/sort
Content-Type: application/json

{
    "sort": [
        {
            "id": "64050589a42711f0d5c7eec8",
            "seqNo": 11
        },
        {
            "id": "64050e6fa42711f0d5c7eed4",
            "seqNo": 12
        }
    ]
}